Attribute VB_Name = "ModGlobals"
Option Explicit

Global NonOpFlag As Integer
Global EmergencyOpFlag As Integer
Global ElectiveOpFlag As Integer
Global Organ As Integer
Global Flag As Integer
Global OpFlag As Integer
Global ABGFlag As Integer
Global HemodynamicsFlag As Integer
Global REEFlag As Integer
Global ApacheFlag As Integer
Global RenalFlag As Integer
Global AminoglycosideFlag As Integer
Global TheophFlag As Integer
Global PDCFlag As Integer
Global Dw As Single
Global CF As Single
Global w As Single
Global w1 As Single
Global w2 As Single
Global w3 As Single
Global w4 As Single
Global X As Single
Global Y As Single
Global z As Single
Global nPaO2 As Single
Global naAdif As Single
Global j8 As Single
Global LastName As String
Global FirstName As String
Global MiddleName As String
Global Age As Single
Global Weight As Single
Global Wtkg As Single
Global BMI As Single
Global IBW As Single
Global ABW As Single
Global Heightt As Single
Global Htcm As Single
Global Sex As Integer
Global Systolic As Single
Global Diastolic As Single
Global MAP As Single
Global AR As Single
Global RR As Single
Global Temp As Single
Global BSA As Single
Global FiO2 As Single
Global Patm As Single
Global SpO2 As Single
Global PaO2 As Single
Global corPaO2 As Single
Global PaCO2 As Single
Global EtCO2 As Single
Global SaO2 As Single
Global CaO2 As Single
Global CcO2 As Single
Global pH As Single
Global HCO3 As Single
Global PvO2 As Single
Global PvCO2 As Single
Global SvO2 As Single
Global CvO2 As Single
Global AVO2dif As Single
Global PaO2_AaDif As Single
Global PaO2FiO2 As Single
Global AO2 As Single
Global Aadif As Single
Global Qs_Qt As Single
Global Creatinine As Single
Global BUN As Single
Global Sodium As Single
Global Potassium As Single
Global Chloride As Single
Global CO2 As Single
Global EstimatedCrCl As Single
Global ActualCrCl As Single
Global TimedUrine As Single
Global VolumeUrine As Single
Global UCreatinine As Single
Global uSodium As Single
Global uPotassium As Single
Global uChloride As Single
Global uCO2 As Single
Global Calcium As Single
Global Magnesium As Single
Global Phosphorus As Single
Global RFI As Single
Global FeNa As Single
Global AG As Single
Global AGG As Single
Global BUN_Cr As Single
Global Sosm As Single
Global CalcSosm As Single
Global Osmgap As Single
Global Glucose As Single
Global UricAcid As Single
Global Uosm As Single
Global Deficit As Single
Global Cellular As Single
Global Volume As Single
Global NaClMeq As Single
Global Lipids As Single   'Triglycerides!
Global Hb As Single
Global Hematocrit As Single
Global WBC As Single
Global RBC As Single
Global CO As Single
Global CI As Single
Global FickCI As Single
Global REE As Single
Global AVCO2Diff_R7 As Single
Global StrokeVolume As Single
Global RAsyst As Single
Global RAdiast As Single
Global RVsyst As Single
Global RVdiast As Single
Global PAPsys As Single
Global PAPdias As Single
Global PAPmean As Single
Global CVP As Single
Global PCWP As Single
Global SI As Single
Global LCW As Single
Global RVSWI As Single
Global RCW As Single
Global LVSWI As Single
Global SVRI As Single
Global PVRI As Single
Global Vd_Vt As Single
Global VdVt As Single
Global DO2 As Single
Global VO2i As Single
Global VO2iMeasured As Single
Global RQ As Single
Global O2ext As Single
Global sSVCSO2 As Single
Global iSVCSO2 As Single
Global RASO2 As Single
Global RVSO2 As Single
Global PASO2 As Single
Global CSSO2 As Single
Global PCSO2 As Single
Global S3_JVD As String  'YN
Global spAMI As String
Global MoPostMi As Single
Global PVC As String
Global notNSR As String
Global over70 As String
Global ERSx As String
Global ChestAbdAort As String
Global AorticStenosis As String
Global AnyComorbid As String
Global CardiacMorbidity As Single
Global Glasgow As Integer
Global Eyes As Integer
Global Verbal As Integer
Global Motor As Integer
Global PDC As Single
Global CHP As Single
Global ARF As Integer
Global Apache2 As Single
Global ApacheIIMortality As Single
Global Stress As Single
Global BEE As Single
Global MaxFluidVol As Single
Global TPNvol As Single
Global Dextrose As Single
Global Fat As Single
Global Fatkcal As Single
Global CHOkcal As Single
Global Protein As Single
Global ProtFact As Single
Global ccDextrose As Single
Global ccFat As Single
Global ccProtein As Single
Global gmProtein As Single
Global gmN2 As Single
Global kcal_N2 As Single
Global TP As Single
Global Albumin As Single
Global COP As Single
Global COP_PCWP As Single
Global PeakAirwayPressure As Single
Global PlateauPressure As Single
Global VT As Single
Global IFR As Single
Global PEEPe As Single
Global PEEPi As Single
Global SwanGanz As String
Global PCWPi As Single
Global PCWPe As Single
Global PCWPc As Single
Global Raw As Single
Global Sgaw As Single
Global StaticCompliance As Single
Global DynamicCompliance As Single
Global I_Eratio As String
'Aminophyline
Global CO1 As Single
Global CD1 As Single
Global TheophLevel As Single
Global Multi As Single
Global TheophPoLD As Single
Global TheophPoLevel As Single
Global ConditionFactor As Single
Global AminoDosage As String
Global AminoDiseaseSev As String
Global MgDay As Single
Global RO As Single  'TheophMaintDose
Global MGHR As Single    'TheopMg_hr
Global Css As Single
Global C1 As Single
Global C2 As Single
Global T7 As Single
Global TimeA As Single
Global TimeB As Single
Global CL1 As Single
Global C3 As Single   'DesiredTheop
Global VI1 As Single 'ccTheoph
Global r2 As Single
Global L3 As Single
Global NewDosageTheoph As Single
Global NewInfusionRateTheoph As Single
Global TheophDosage As Single
Global DesiredTheophLevel As Single
Global ActualTheophLevel As Single
Global NewTheophDosage As Single
'Aminoglycosides
Global AminoRx As String
Global Hydration As String
Global InfusionTime As Single
Global DsSeverity As String
Global CreatClInput As String
Global CrCl As Single
Global Neut As String
Global Neutropenia As String
Global AminoDosingInterval As Single
Global AminoMaintDose As Single
Global AminoPE As Single  '?
Global AminoTR As Single
Global AminogLD As Single
Global AminoNewLoading As Single
Global AminoNewMaintDose As Single
Global AminoNewDosingInterval As Single
Global AminoPredPeak As Single
Global AminoPredTrough As Single
Global AminoActualPeak As Single
Global AminoActualTrough As Single
Global AminoKd As Single
Global AminoHalfLife As Single
Global AminoVolDistribution As Single
Global vd As Single
Global AminoPeakDraw_RxTime As Single
Global AminoAdjustedPeak As Single
Global AminoAdjustedTrough As Single
Global KDAminog As Single
Global DIAminog As Single
Global MDAminog As Single
Global MDAminog1 As Single
Global MDAminog2 As Single
Global MDAminog3 As Single
Global PE As Single
Global PE8 As Single
Global PE12 As Single
Global PE24 As Single
Global TR As Single
Global TR8 As Single
Global TR12 As Single
Global TR24 As Single
Global t As Single
Global Pk As Single
Global TA As Single
Global TB As Single
Global TH As Single

Global dVancoTrough As Single
Global dVancoPeak As Single
Global eVancoTrough As Single
Global eVancoPeak As Single
Global k0  As Single
Global tau  As Single
Global tinf  As Single
Global vancttime  As Single
Global vancPtime  As Single
Global k12  As Single
Global k21  As Single
Global vVc As Single
Global vkd As Single
'(hybrid distribution rate constant) = (k21 x k10)/kel
Global k10 As Single
Global kel As Single
Global vVd As Single
Global REEcalcu As Single
Public Sub Delay(HowLong As Date)
Dim TempTime As String
TempTime = DateAdd("s", HowLong, Now)
While TempTime > Now
DoEvents 'Allows windows to handle other stuff
Wend
End Sub
